instance_provision: 'on_demand'
gce_datacenter: 'us-east1-b'
gce_network: 'qa-vpc'
gce_image_username: 'scylla-test'

gke_cluster_version: '1.15.12-gke.20'
gke_cluster_n_nodes: 3

gce_instance_type_db: 'n1-standard-8'
gce_root_disk_type_db: 'pd-ssd'
gce_root_disk_size_db: 50
gce_n_local_ssd_disk_db: 3

n_db_nodes: 3

k8s_scylla_operator_docker_image: 'scylladb/scylla-operator:nightly'
k8s_cert_manager_version: '1.0.3'
scylla_version: '4.2.1'
scylla_mgmt_agent_version: '2.2.0'
k8s_scylla_datacenter: 'us-east1-b'
k8s_scylla_rack: 'us-east1'
k8s_scylla_cluster_name: 'sct-cluster'
k8s_scylla_cpu_n: 6
k8s_scylla_mem_gi: 16
k8s_scylla_disk_gi: 500

k8s_loader_cluster_name: 'sct-loaders'
k8s_loader_cpu_n: 3
k8s_loader_mem_gi: 12
gce_instance_type_loader: 'e2-standard-4'

n_loaders: 1

gce_image_monitor: 'https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-7'
gce_instance_type_monitor: 'e2-medium'
gce_root_disk_type_monitor: 'pd-standard'
gce_root_disk_size_monitor: 50
gce_n_local_ssd_disk_monitor: 0

n_monitor_nodes: 1

user_credentials_path: '~/.ssh/scylla-test'
use_preinstalled_scylla: true
backtrace_decoding: false

append_scylla_args: ''
