# Namespace where the Scylla Cluster will be created
apiVersion: v1
kind: Namespace
metadata:
  name: scylla

---

# Role for scylla members.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ${SCT_K8S_SCYLLA_CLUSTER_NAME}-member
  namespace: scylla
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - "apps"
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - scylla.scylladb.com
    resources:
      - scyllaclusters
    verbs:
      - get

---

# ServiceAccount for scylla members.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${SCT_K8S_SCYLLA_CLUSTER_NAME}-member
  namespace: scylla

---

# RoleBinding for scylla members.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ${SCT_K8S_SCYLLA_CLUSTER_NAME}-member
  namespace: scylla
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ${SCT_K8S_SCYLLA_CLUSTER_NAME}-member
subjects:
  - kind: ServiceAccount
    name: ${SCT_K8S_SCYLLA_CLUSTER_NAME}-member
    namespace: scylla

---

# Scylla Cluster
apiVersion: scylla.scylladb.com/v1alpha1
kind: ScyllaCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: ${SCT_K8S_SCYLLA_CLUSTER_NAME}
  namespace: scylla
spec:
  version: ${SCT_SCYLLA_VERSION}
  agentVersion: ${SCT_SCYLLA_MGMT_AGENT_VERSION}
  cpuset: true
  sysctls:
    - "fs.aio-max-nr=2097152"
  network:
    hostNetworking: true
  datacenter:
    name: ${SCT_K8S_SCYLLA_DATACENTER}
    racks:
      - name: ${SCT_K8S_SCYLLA_RACK}
        scyllaConfig: "scylla-config"
        scyllaAgentConfig: "scylla-agent-config"
        members: 0
        storage:
          storageClassName: local-raid-disks
          capacity: ${SCT_K8S_SCYLLA_DISK_GI}Gi
        resources:
          limits:
            cpu: ${SCT_K8S_SCYLLA_CPU_N}
            memory: ${SCT_K8S_SCYLLA_MEM_GI}Gi
          requests:
            cpu: ${SCT_K8S_SCYLLA_CPU_N}
            memory: ${SCT_K8S_SCYLLA_MEM_GI}Gi
        placement:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: failure-domain.beta.kubernetes.io/zone
                    operator: In
                    values:
                      - ${SCT_K8S_SCYLLA_DATACENTER}
          tolerations:
            - key: role
              operator: Equal
              value: scylla-clusters
              effect: NoSchedule
