apiVersion: v1
kind: Namespace
metadata:
  name: sct-loaders

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${SCT_K8S_LOADER_CLUSTER_NAME}
  namespace: sct-loaders
spec:
  selector:
    matchLabels:
      app: ${SCT_K8S_LOADER_CLUSTER_NAME}
  serviceName: ${SCT_K8S_LOADER_CLUSTER_NAME}
  replicas: ${SCT_N_LOADERS}
  template:
    metadata:
      labels:
        app: ${SCT_K8S_LOADER_CLUSTER_NAME}
    spec:
      containers:
        - name: cassandra-stress
          image: scylladb/scylla:4.3.rc1
          command:
            - "/bin/cat"
          tty: true
          volumeMounts:
            - mountPath: /usr/bin/docker
              name: docker-binary
            - mountPath: /var/run/docker.sock
              name: docker-socket
          resources:
            limits:
              cpu: ${SCT_K8S_LOADER_CPU_N}
              memory: ${SCT_K8S_LOADER_MEM_GI}Gi
            requests:
              cpu: ${SCT_K8S_LOADER_CPU_N}
              memory: ${SCT_K8S_LOADER_MEM_GI}Gi
          securityContext:
            privileged: true
      volumes:
        - name: docker-binary
          hostPath:
            path: /usr/bin/docker
            type: File
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                    - ${SCT_K8S_SCYLLA_DATACENTER}
      tolerations:
        - key: role
          operator: Equal
          value: ${SCT_K8S_LOADER_CLUSTER_NAME}
          effect: NoSchedule
